cbioportal_data_downloader:
  output_directory: database_cbioportal
  list_studies: False
  cbioportal_api:
    base_url: https://www.cbioportal.org/webservice.do
    cancer_studies: cmd=getCancerStudies
  cbioportal_download_url: http://download.cbioportal.org
  logger:
    formatters:
      DEBUG: "%(asctime)s [%(levelname)7s][%(name)48s][%(module)32s, %(lineno)4s] %(message)s"
      INFO: "%(asctime)s [%(levelname)7s][%(name)48s] %(message)s"
    loglevel: DEBUG
  multithreading: True
proteindb:
   filter_info:
      filter_column: 'Tumor_Sample_Barcode'
      accepted_values: 'all'
      split_by_filter_column: False
      clinical_sample_file: ''
   
  